[workspace]
members = [
    "core",
    "cli",
    "wasm"
]
resolver = "2"

[workspace.package]
version = "0.4.0"
edition = "2021"
authors = ["kilopal"]
description = "A blazing-fast, memory-safe tool to strip AI provenance watermarks (C2PA & Unicode) from text and images."

[profile.release]
opt-level = "z" # Optimize for size (critical for WASM)
lto = true
codegen-units = 1
panic = "abort"
